### ISSUE TITLE
Request for references

### ISSUE THREAD

**Issue by seonjunn** [junstar92/parallel_programming_study#1]
I bumped into this interesting repo.
Were there any materials(book, lecture, blog, etc.) you used during the study?

Best regards

**Comment by junstar92** [comment]
@seonjunn I mainly referered to the books below.
- An Introduction to Parallel Programming, Peter Pacheco
- Programming Massively Parallel Processors: A Hands-on Approach, David B. Kirk, Wen-mei W. Hwu
