### ISSUE TITLE
Question about matrixAdd example code

### ISSUE THREAD

**Issue by vincenthanna** [junstar92/parallel_programming_study#2]
I'm learning CUDA well with your code. Thanks a lot.

code for rows and columns in matrixAdd example seems a bit odd. 
It looks like the ROW variable should use .y and the COL should use .x. (if M is row size and N is column size)

```C++
__global__ void matrixAdd(const float* A, const float* B, float* C, int M, int N) {
    int ROW = blockIdx.y * blockDim.y + threadIdx.y;
    int COL = blockIdx.x * blockDim.x + threadIdx.x;
    int idx = ROW * N + COL;

    if (ROW < M && COL < N) {
        C[idx] = A[idx] + B[idx];
    }
}

```

https://github.com/junstar92/parallel_programming_study/blob/9886cc1e6f630c7b89b402ad2ffa60653ce8edfa/CUDA/matrixAdd/matrixAdd.cu#L114

**Comment by junstar92** [comment]
@vincenthanna (한국분이신 것 같아서..) 영어로 정확한 의도를 표현하기가 어려워 한국어로 전달드립니다 !

일단 결론부터 이야기하자면 코드 자체에 문제가 있는 것은 아닙니다. 각 스레드가 액세스하는 메모리 주소는 사실 thread ID를 어떻게 매핑하느냐에 따라서 얼마든지 달라질 수 있으며, @vincenthanna 께서 수정해주신 코드도 맞습니다. 다시 말하자면, thread ID와 memory access 간의 매핑은 구현하기에 달려있습니다.

조금 더 자세히 이야기하자면 제가 작성한 코드가 global memory 액세스 관점에서 coalesced memory access 패턴이 아니기 때문에 작성해주신 코드가 사실 더 일반적으로 사용되는 패턴이긴 합니다. 실제로 ncu를 통해서 memory request 수를 측정해보면 제가 작성한 코드가 더 많습니다 (제 코드가 더 비효율적이라는 것을 의미합니다).

추가적으로 저도 궁금해서 제 코드와 작성자분의 코드의 global memory load/store throughput을 측정해봤는데, throughput은 제가 작성한 코드가 2~3배 더 높게 측정되었습니다. 조금 놀라운 결과였는데, 왜 그런지는 자세한 분석이 필요하겠지만 제 추측으로는 memory access 패턴보다 cache hit 측면에서 더 효율이 좋았던게 아닌가 싶습니다.

**Comment by vincenthanna** [comment]
1차원 데이터 배열이므로 매핑방식이 배열에 잘 접근만 한다면 문제가 되지 않는 것으로 이해하였습니다.
coalesced memory access 도 처음 접해본 명칭인데 배울것이 참 많네요.
정성어린 답변에 깊은 감사 드립니다.
